services:
  - type: web
    name: xau-ai-alert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_alert:app --timeout 120
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: false
